---
- name: Verifica se as variáveis estão configuradas
  fail: "[Target Directory] and/or [Openshift host] não estão definidos. Edite o arquivo vars.yml"
  when: (workdir is undefinied) or (openshift is undefinied)

- name: Logar no Openshift como Administrador
  shell: "oc login --insecure-skip-tls-verify=true -u {{ admin_username }} -p {{ admin_password }} {{ openshift }}"
  tags:
     - openshift
     - admin

- name: Ajustar SCC
  shell: "oc patch scc restricted -p '{\"runAsUser\":{\"type\":\"RunAsAny\"}}'"
  when: adjust_scc

- name: Criar Workdir
  file:
     path: "{{ workdir }}"
     state: directory

- name: Checkout source no Git
  git:
     repo: "https://github.com/inacioikeda/{{ item.name }}"
     dest: "{{ workdir }}/{{ item.name }}"
     update: yes
  with_items: "{{ openshift_deploy }}"
  when: "{{ clone_modules }}"
  tags:
     - git

- name: Compilar projetos Java
  shell: "mvn -f {{ workdir }}/{{ item.name }}/pom.xml package"
  with_items: "{{ openshift_deploy }}"
  when: "item.project == 'java'"
  tags:
     - compile

- name: Compilar projetos NodeJS
  shell: "npm --prefix {{ workdir }}/{{ item.name }}  install {{ workdir }}/{{ item.name }}"
  with_items: "{{ openshift_deploy }}"
  when: "item.project == 'node'"
  tags:
     - compile